// components/store/Navbar.tsx
"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import Link from "next/link";
import { ShoppingBag, Search, User, Menu, X, Heart } from "lucide-react";
import { useCart } from "@/lib/cartStore";

const navLinks = [
  { label: "MEN", href: "/shop?gender=Men" },
  { label: "WOMEN", href: "/shop?gender=Women" },
  { label: "SNEAKERS", href: "/shop?category=Shoes" },
  { label: "NEW DROPS", href: "/shop?sort=newest" },
  { label: "SALE", href: "/shop", color: "text-[#E63946]" },
];

export default function Navbar() {
  const [scrolled, setScrolled] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  const { totalItems } = useCart();

  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  return (
    <>
      <motion.nav
        className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
          scrolled ? "bg-white shadow-md" : "bg-white"
        }`}
        initial={{ y: -100 }}
        animate={{ y: 0 }}
        transition={{ duration: 0.5 }}
      >
        <div className="bg-[#0A0A0A] text-white text-center text-xs py-2 tracking-widest">
          FREE SHIPPING ON ORDERS ABOVE ₹599 🚀
        </div>

        <div className="max-w-7xl mx-auto px-4 md:px-8">
          <div className="flex items-center justify-between h-16">
            <button className="md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">
              {menuOpen ? <X size={24} /> : <Menu size={24} />}
            </button>

            <Link href="/" className="text-2xl font-black tracking-tight">
              DRIP<span className="text-[#E63946]">STORE</span>
            </Link>

            <div className="hidden md:flex items-center gap-8">
              {navLinks.map((link) => (
                <Link
                  key={link.label}
                  href={link.href}
                  className={`text-sm font-semibold tracking-widest hover:text-[#E63946] transition-colors ${
                    link.color || "text-[#0A0A0A]"
                  }`}
                >
                  {link.label}
                </Link>
              ))}
            </div>

            <div className="flex items-center gap-4">
              <button onClick={() => setSearchOpen(!searchOpen)} aria-label="Open search">
                <Search size={20} className="hover:text-[#E63946] transition-colors" />
              </button>
              <Link href="/profile" aria-label="Profile">
                <User size={20} className="hover:text-[#E63946] transition-colors" />
              </Link>
              <Link href="/profile?tab=wishlist" aria-label="Wishlist">
                <Heart size={20} className="hover:text-[#E63946] transition-colors" />
              </Link>
              <Link href="/cart" className="relative" aria-label="Cart">
                <ShoppingBag size={20} className="hover:text-[#E63946] transition-colors" />
                {totalItems > 0 && (
                  <motion.span
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    className="absolute -top-2 -right-2 bg-[#E63946] text-white text-xs w-4 h-4 rounded-full flex items-center justify-center font-bold"
                  >
                    {totalItems > 9 ? "9+" : totalItems}
                  </motion.span>
                )}
              </Link>
            </div>
          </div>
        </div>

        <AnimatePresence>
          {searchOpen && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: "auto", opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              className="border-t border-gray-100 bg-white px-4 md:px-8 py-4"
            >
              <input
                autoFocus
                type="text"
                placeholder="Search for t-shirts, shoes, hoodies..."
                className="w-full text-lg outline-none border-b-2 border-[#E63946] pb-2 bg-transparent"
              />
            </motion.div>
          )}
        </AnimatePresence>
      </motion.nav>

      <AnimatePresence>
        {menuOpen && (
          <motion.div
            initial={{ x: "-100%" }}
            animate={{ x: 0 }}
            exit={{ x: "-100%" }}
            transition={{ type: "tween", duration: 0.3 }}
            className="fixed inset-0 z-40 bg-white pt-20 px-6"
          >
            <div className="flex flex-col gap-6 mt-4">
              {navLinks.map((link) => (
                <Link
                  key={link.label}
                  href={link.href}
                  onClick={() => setMenuOpen(false)}
                  className={`text-2xl font-bold tracking-widest ${
                    link.color || "text-[#0A0A0A]"
                  }`}
                >
                  {link.label}
                </Link>
              ))}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}

// frontend/src/components/Navbar.vue
<template>
  <header 
    class="fixed top-0 left-0 w-full z-40 transition-all duration-300"
    :class="{ 'glass': isScrolled, 'py-2': isScrolled, 'py-5': !isScrolled }"
  >
    <div class="container mx-auto px-6 flex items-center justify-between">
      
      <!-- Logo -->
      <RouterLink to="/" class="text-3xl font-display font-black tracking-widest text-white group">
        <span class="anim-gradient gradientShift inline-block group-hover:scale-105 transition-transform" 
              style="background-image: var(--grad-neon); -webkit-background-clip: text; color: transparent;">
          ASH<span class="text-white drop-shadow-[0_0_10px_rgba(255,255,255,0.5)]">KAIR</span>
        </span>
      </RouterLink>

      <!-- Desktop Nav -->
      <nav class="hidden md:flex items-center gap-8">
        <RouterLink 
          to="/" 
          class="nav-link relative font-bold text-xs tracking-widest uppercase text-gray-300 hover:text-white transition-colors"
          active-class="active text-white"
        >
          Home
        </RouterLink>
        <RouterLink 
          to='/products' 
          class="nav-link relative font-bold text-xs tracking-widest uppercase text-gray-300 hover:text-white transition-colors"
          active-class="active text-white"
        >
          Shop
        </RouterLink>
        <RouterLink to="/products?badge=SALE" class="nav-link relative font-bold text-xs tracking-widest uppercase text-red-400 hover:text-red-300 transition-colors">
          Sale 🔥
        </RouterLink>
      </nav>

      <!-- Actions -->
      <div class="flex items-center gap-2">
        <button 
          @click="searchOpen = true"
          class="w-10 h-10 rounded-full flex items-center justify-center bg-white/5 hover:bg-white/10 transition-colors text-lg"
        >
          🔍
        </button>
        <RouterLink 
          to="/wishlist"
          class="w-10 h-10 rounded-full flex items-center justify-center bg-white/5 hover:bg-white/10 transition-colors relative text-lg"
        >
          🤍
          <span v-if="wishlistCount > 0"
            class="absolute -top-1 -right-1 bg-[#ff2d78] text-white text-[10px] font-bold w-5 h-5 flex items-center justify-center rounded-full">
            {{ wishlistCount }}
          </span>
        </RouterLink>
        <button 
          @click="toggleCart(true)" 
          class="w-10 h-10 rounded-full flex items-center justify-center bg-white/5 hover:bg-white/10 transition-colors relative group text-lg"
        >
          🛒
          <span 
            v-if="cartCount > 0"
            class="absolute -top-1 -right-1 bg-neon-orange text-white text-[10px] font-bold w-5 h-5 flex items-center justify-center rounded-full group-hover:scale-110 transition-transform"
            :class="{ 'anim-heartbeat': isAnimating }"
          >
            {{ cartCount }}
          </span>
        </button>
        <RouterLink to="/login" v-if="!authStore.isLoggedIn" class="hidden md:flex btn-glass hover:text-white !py-2 !px-6 text-xs items-center justify-center">
          SIGN IN
        </RouterLink>
        <RouterLink to="/profile" v-else class="hidden md:flex btn-glass hover:text-white !py-2 !px-6 text-xs items-center justify-center">
          MY ACCOUNT
        </RouterLink>
        <button 
          @click="mobileOpen = !mobileOpen"
          class="md:hidden w-10 h-10 rounded-full flex items-center justify-center bg-white/5 hover:bg-white/10 transition-colors"
        >
          <div class="flex flex-col gap-1.5 w-4">
            <span class="block h-0.5 bg-white transition-all duration-300" :class="mobileOpen ? 'rotate-45 translate-y-2' : ''" />
            <span class="block h-0.5 bg-white transition-all duration-300" :class="mobileOpen ? 'opacity-0 scale-x-0' : ''" />
            <span class="block h-0.5 bg-white transition-all duration-300" :class="mobileOpen ? '-rotate-45 -translate-y-2' : ''" />
          </div>
        </button>
      </div>

    </div>

    <Transition name="slideDown">
      <div v-if="mobileOpen" class="md:hidden glass border-t border-white/10 px-6 py-6 flex flex-col gap-4">
        <RouterLink to="/" @click="mobileOpen = false"
          class="font-bold text-sm tracking-widest uppercase text-gray-300 hover:text-neon-orange transition-colors">Home</RouterLink>
        <RouterLink to="/products" @click="mobileOpen = false"
          class="font-bold text-sm tracking-widest uppercase text-gray-300 hover:text-neon-orange transition-colors">Shop</RouterLink>
        <RouterLink to="/wishlist" @click="mobileOpen = false"
          class="font-bold text-sm tracking-widest uppercase text-gray-300 hover:text-neon-orange transition-colors">Wishlist</RouterLink>
        <RouterLink to="/orders" @click="mobileOpen = false"
          class="font-bold text-sm tracking-widest uppercase text-gray-300 hover:text-neon-orange transition-colors">My Orders</RouterLink>
        <div class="border-t border-white/10 pt-4">
          <RouterLink v-if="!authStore.isLoggedIn" to="/login" @click="mobileOpen = false"
            class="btn-glow-orange w-full block text-center py-3 text-xs tracking-widest">SIGN IN</RouterLink>
          <RouterLink v-else to="/profile" @click="mobileOpen = false"
            class="btn-glass w-full block text-center py-3 text-xs tracking-widest">MY ACCOUNT</RouterLink>
        </div>
      </div>
    </Transition>

    <!-- Search Overlay -->
    <Transition name="fade">
      <div v-if="searchOpen" class="fixed inset-0 z-50 flex items-center justify-center bg-black/95 backdrop-blur-xl" @click.self="closeSearch">
        <button @click="closeSearch" class="absolute top-8 right-8 text-6xl font-light text-white hover:text-[#ff6b00] transition-colors">×</button>
        <div class="w-full max-w-4xl px-6">
          <form @submit.prevent="doSearch">
            <input v-model="searchQuery" type="text" placeholder="SEARCH THE FUTURE..." 
              class="w-full bg-transparent border-b-2 border-white/20 text-5xl md:text-6xl font-display text-white placeholder:text-white/20 outline-none pb-4 focus:border-[#ff6b00] transition-colors"
              autofocus />
          </form>
          <div class="mt-8 flex flex-wrap gap-3 items-center">
            <span class="text-xs font-bold text-gray-500 tracking-widest">POPULAR //</span>
            <span v-for="tag in popularTags" :key="tag.label"
              @click="quickSearch(tag.query)"
              class="badge-neon px-3 py-1 cursor-pointer hover:scale-105 transition-transform"
              :class="tag.cls">{{ tag.label }}</span>
          </div>
        </div>
      </div>
    </Transition>
  </header>
</template>

<script setup>
import { ref, watch, computed, onMounted, onUnmounted } from 'vue'
import { RouterLink, useRouter } from 'vue-router'
import { useAuthStore } from '../stores/authStore'
import { useCartStore } from '../stores/cartStore'
import { useWishlistStore } from '../stores/wishlistStore'
import { toggleCart } from '../composables/useCart'

const router = useRouter()
const authStore = useAuthStore()
const cartStore = useCartStore()
const wishlistStore = useWishlistStore()
const isScrolled = ref(false)
const searchOpen = ref(false)
const mobileOpen = ref(false)
const searchQuery = ref('')

const cartCount = computed(() => {
  return cartStore.totalItems
})
const wishlistCount = computed(() => wishlistStore.items.length)

const popularTags = [
  { label: 'SNEAKERS', query: 'Sneakers', cls: 'badge-hot' },
  { label: 'HOODIES', query: 'Hoodies', cls: 'badge-limited' },
  { label: 'T-SHIRTS', query: 'T-Shirts', cls: 'badge-new' },
  { label: 'JACKETS', query: 'Jackets', cls: 'badge-best' }
]

const isAnimating = ref(false)
watch(cartCount, (newVal, oldVal) => {
  if (newVal > oldVal) {
    isAnimating.value = true
    setTimeout(() => isAnimating.value = false, 1000)
  }
})

const closeSearch = () => {
  searchOpen.value = false
  searchQuery.value = ''
}

const doSearch = () => {
  if (!searchQuery.value.trim()) return
  router.push({ path: '/products', query: { search: searchQuery.value.trim() } })
  closeSearch()
}

const quickSearch = (query) => {
  router.push({ path: '/products', query: { search: query } })
  closeSearch()
}

const handleScroll = () => {
  isScrolled.value = window.scrollY > 20
}

onMounted(() => {
  window.addEventListener('scroll', handleScroll)
})

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll)
})
</script>

<style scoped>
.nav-link::after {
  content: '';
  position: absolute;
  bottom: -4px;
  left: 0;
  width: 0%;
  height: 2px;
  background: var(--grad-orange);
  transition: width 0.3s var(--ease-smooth);
}
.nav-link:hover::after,
.nav-link.active::after {
  width: 100%;
}

.slideDown-enter-active, .slideDown-leave-active { transition: all 0.3s var(--ease-smooth); }
.slideDown-enter-from, .slideDown-leave-to { opacity: 0; transform: translateY(-8px); }

.fade-enter-active, .fade-leave-active { transition: opacity 0.3s ease; }
.fade-enter-from, .fade-leave-to { opacity: 0; }
</style>
