// frontend/src/components/Footer.vue
<template>
  <footer class="bg-[#0d0d0d] text-white mt-16">
    <div class="container mx-auto px-4 py-12">
      <div class="grid grid-cols-1 md:grid-cols-4 gap-8">
        <!-- Column 1: Brand -->
        <div>
          <h3 class="text-2xl font-black text-[#ff6b00] mb-4">SHOPZONE</h3>
          <p class="text-gray-400 text-sm mb-4">
            Your one-stop destination for licensed pop culture merchandise. Wear your fandom with pride!
          </p>
          <div class="flex gap-3">
            <a href="#" class="w-10 h-10 bg-gray-800 rounded-full flex items-center justify-center hover:bg-[#ff6b00] transition">
              <span>📸</span>
            </a>
            <a href="#" class="w-10 h-10 bg-gray-800 rounded-full flex items-center justify-center hover:bg-[#ff6b00] transition">
              <span>🐦</span>
            </a>
            <a href="#" class="w-10 h-10 bg-gray-800 rounded-full flex items-center justify-center hover:bg-[#ff6b00] transition">
              <span>▶️</span>
            </a>
          </div>
        </div>

        <!-- Column 2: Shop -->
        <div>
          <h4 class="font-bold mb-4 uppercase tracking-wide">SHOP</h4>
          <ul class="space-y-2 text-sm">
            <li><RouterLink to="/products?category=T-Shirts" class="text-gray-400 hover:text-[#ff6b00] transition">T-Shirts</RouterLink></li>
            <li><RouterLink to="/products?category=Shirts" class="text-gray-400 hover:text-[#ff6b00] transition">Shirts</RouterLink></li>
            <li><RouterLink to="/products?category=Joggers" class="text-gray-400 hover:text-[#ff6b00] transition">Joggers</RouterLink></li>
            <li><RouterLink to="/products?category=Sneakers" class="text-gray-400 hover:text-[#ff6b00] transition">Sneakers</RouterLink></li>
            <li><RouterLink to="/products?category=Accessories" class="text-gray-400 hover:text-[#ff6b00] transition">Accessories</RouterLink></li>
          </ul>
        </div>

        <!-- Column 3: Help -->
        <div>
          <h4 class="font-bold mb-4 uppercase tracking-wide">HELP</h4>
          <ul class="space-y-2 text-sm">
            <li><a href="#" class="text-gray-400 hover:text-[#ff6b00] transition">Track Order</a></li>
            <li><a href="#" class="text-gray-400 hover:text-[#ff6b00] transition">Returns</a></li>
            <li><a href="#" class="text-gray-400 hover:text-[#ff6b00] transition">Size Guide</a></li>
            <li><a href="#" class="text-gray-400 hover:text-[#ff6b00] transition">FAQs</a></li>
            <li><a href="#" class="text-gray-400 hover:text-[#ff6b00] transition">Contact Us</a></li>
          </ul>
        </div>

        <!-- Column 4: Newsletter -->
        <div>
          <h4 class="font-bold mb-4 uppercase tracking-wide">CONNECT</h4>
          <p class="text-gray-400 text-sm mb-3">Subscribe to get exclusive offers & updates</p>
          <form class="flex gap-2">
            <input
              type="email"
              placeholder="Enter your email"
              class="flex-1 px-3 py-2 bg-gray-800 rounded text-sm focus:outline-none focus:ring-2 focus:ring-[#ff6b00]"
            />
            <button
              type="submit"
              class="px-4 py-2 bg-[#ff6b00] rounded font-bold hover:bg-[#ff8533] transition"
            >
              Subscribe
            </button>
          </form>
        </div>
      </div>

      <!-- Bottom Bar -->
      <div class="border-t border-gray-800 mt-8 pt-8 flex flex-col md:flex-row justify-between items-center text-sm text-gray-400">
        <p>© 2026 ShopZone. All rights reserved.</p>
        <div class="flex gap-6 mt-4 md:mt-0">
          <a href="#" class="hover:text-[#ff6b00] transition">Privacy Policy</a>
          <a href="#" class="hover:text-[#ff6b00] transition">Terms of Use</a>
        </div>
      </div>
    </div>
  </footer>
</template>

<script setup>
import { RouterLink } from 'vue-router'
</script>

// components/store/Footer.tsx
"use client";

import Link from "next/link";
import { useState } from "react";
import { Share2, Mail, Heart, Send } from "lucide-react";
import toast from "react-hot-toast";

export default function Footer() {
  const [email, setEmail] = useState("");

  const handleSubscribe = (e: React.FormEvent) => {
    e.preventDefault();
    if (!email.trim()) return;
    toast.success("Subscribed successfully!");
    setEmail("");
  };

  return (
    <footer className="bg-[#0A0A0A] text-white">
      <div className="border-b border-white/10 py-12 px-4 md:px-16">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
          <div>
            <h3 className="text-2xl font-black tracking-tight mb-1">JOIN THE CLUB</h3>
            <p className="text-gray-400 text-sm">Get exclusive drops, offers & style tips</p>
          </div>
          <form onSubmit={handleSubscribe} className="flex w-full md:w-auto">
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="Enter your email"
              className="bg-white/10 border border-white/20 px-4 py-3 text-sm w-full md:w-72 outline-none focus:border-[#E63946]"
              required
            />
            <button className="bg-[#E63946] px-6 py-3 text-sm font-bold tracking-widest hover:bg-red-700 transition-colors whitespace-nowrap">
              SUBSCRIBE
            </button>
          </form>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 md:px-16 py-12 grid grid-cols-2 md:grid-cols-4 gap-8">
        <div>
          <h4 className="font-black text-lg tracking-tight mb-4">
            DRIP<span className="text-[#E63946]">STORE</span>
          </h4>
          <p className="text-gray-400 text-sm leading-relaxed">
            Homegrown Indian brand. Crafted with intent, curated for you.
          </p>
          <div className="flex gap-4 mt-4">
            <Share2 size={18} className="text-gray-400 hover:text-[#E63946] cursor-pointer transition-colors" />
            <Mail size={18} className="text-gray-400 hover:text-[#E63946] cursor-pointer transition-colors" />
            <Heart size={18} className="text-gray-400 hover:text-[#E63946] cursor-pointer transition-colors" />
            <Send size={18} className="text-gray-400 hover:text-[#E63946] cursor-pointer transition-colors" />
          </div>
        </div>

        {[
          { title: "SHOP", links: ["Men", "Women", "Sneakers", "New Arrivals", "Sale"] },
          { title: "HELP", links: ["Size Guide", "Track Order", "Returns", "Contact Us", "FAQ"] },
          { title: "COMPANY", links: ["About Us", "Careers", "Press", "Blog", "Sustainability"] },
        ].map((col) => (
          <div key={col.title}>
            <h4 className="font-bold text-xs tracking-widest mb-4 text-gray-400">{col.title}</h4>
            <ul className="space-y-2">
              {col.links.map((link) => (
                <li key={link}>
                  <Link href="#" className="text-sm text-gray-300 hover:text-[#E63946] transition-colors">
                    {link}
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>

      <div className="border-t border-white/10 py-4 px-4 md:px-16">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-2 text-xs text-gray-500">
          <p>© 2026 DripStore. All rights reserved.</p>
          <div className="flex gap-4">
            <Link href="#" className="hover:text-white transition-colors">Privacy Policy</Link>
            <Link href="#" className="hover:text-white transition-colors">Terms of Service</Link>
            <Link href="#" className="hover:text-white transition-colors">Shipping Policy</Link>
          </div>
        </div>
      </div>
    </footer>
  );
}
