// frontend/src/components/ProductCard.vue
<template>
  <div class="card group relative cursor-pointer" @click="goToProduct">
    <div class="relative overflow-hidden bg-gray-100" style="aspect-ratio: 4/5">
      <img :src="product.image_url" :alt="product.name" class="w-full h-full object-cover transition-all duration-500 group-hover:opacity-0 absolute inset-0" />
      <img :src="product.image_url_hover || product.image_url" :alt="product.name" class="w-full h-full object-cover transition-all duration-500 opacity-0 group-hover:opacity-100 group-hover:scale-105" />

      <span
        v-if="product.badge"
        :class="[
          'absolute top-3 left-3 z-10 badge',
          badgeClass
        ]"
      >
        {{ product.badge }}
      </span>

      <span
        v-if="discountPercent > 0"
        class="absolute top-3 right-3 z-10 bg-red-500 text-white text-xs font-black rounded-full w-10 h-10 flex items-center justify-center"
      >
        -{{ discountPercent }}%
      </span>

      <button
        @click.stop="toggleWishlist"
        class="absolute top-12 right-3 z-10 w-8 h-8 rounded-full bg-white/90 flex items-center justify-center shadow transition-all duration-200 hover:scale-110 hover:bg-white"
      >
        <span :class="isWishlisted ? 'text-red-500' : 'text-gray-400'">{{ isWishlisted ? '❤️' : '🤍' }}</span>
      </button>

      <div class="absolute bottom-0 left-0 right-0 bg-black/85 backdrop-blur-sm translate-y-full group-hover:translate-y-0 transition-transform duration-300 p-3 z-10">
        <div class="flex gap-1.5 justify-center mb-2 flex-wrap">
          <button
            v-for="size in sizesArray"
            :key="size"
            @click.stop="selectSize(size)"
            :class="[
              'text-xs font-bold px-2.5 py-1 rounded-md transition-all duration-150',
              selectedSize === size ? 'bg-orange-500 text-white' : 'bg-white/20 text-white hover:bg-white/40'
            ]"
          >
            {{ size }}
          </button>
        </div>
        <button
          @click.stop="addToCart"
          :class="[
            'w-full py-2 rounded-xl text-sm font-bold uppercase tracking-wider transition-all duration-200',
            addedToCart ? 'bg-green-500 text-white animate-pulse-btn' : 'bg-orange-500 hover:bg-orange-600 text-white'
          ]"
        >
          {{ addedToCart ? '✓ ADDED!' : 'ADD TO CART' }}
        </button>
      </div>
    </div>

    <div class="p-3">
      <div class="flex items-center gap-1 mb-1">
        <div class="flex">
          <span v-for="i in 5" :key="i" :class="i <= Math.round(product.rating) ? 'text-orange-400' : 'text-gray-200'" class="text-xs">★</span>
        </div>
        <span class="text-xs text-gray-400">({{ product.reviews }})</span>
      </div>

      <h3 class="font-semibold text-sm text-gray-900 leading-tight mb-2 line-clamp-2 group-hover:text-orange-600 transition-colors">{{ product.name }}</h3>

      <div class="flex items-center gap-2">
        <span class="font-black text-base text-gray-900">₹{{ product.price }}</span>
        <span v-if="product.original_price" class="text-xs text-gray-400 line-through">₹{{ product.original_price }}</span>
        <span v-if="discountPercent > 0" class="text-xs font-bold text-green-500">{{ discountPercent }}% off</span>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useCartStore } from '../stores/cartStore'
import { useToastStore } from '../stores/toastStore'
import { useWishlistStore } from '../stores/wishlistStore'

const props = defineProps({ product: { type: Object, required: true } })

const router = useRouter()
const cart = useCartStore()
const wishlist = useWishlistStore()
const toast = useToastStore()

const selectedSize = ref('')
const addedToCart = ref(false)

const sizesArray = computed(() => {
  if (Array.isArray(props.product.sizes) && props.product.sizes.length) return props.product.sizes
  if (typeof props.product.sizes === 'string' && props.product.sizes.length) return props.product.sizes.split(',')
  return ['S', 'M', 'L', 'XL']
})

const discountPercent = computed(() => {
  if (!props.product.original_price) return 0
  return Math.round(((props.product.original_price - props.product.price) / props.product.original_price) * 100)
})

const isWishlisted = computed(() => wishlist.isWishlisted(props.product.id))

const badgeClass = computed(() => {
  const badge = (props.product.badge || '').toUpperCase()
  if (badge === 'NEW') return 'badge-new'
  if (badge === 'SALE') return 'badge-sale'
  if (badge === 'HOT') return 'badge-hot'
  if (badge === 'BESTSELLER') return 'badge-best'
  return 'badge-limited'
})

function goToProduct() {
  router.push(`/products/${props.product.id}`)
}

function selectSize(size) {
  selectedSize.value = size
}

function addToCart() {
  if (!selectedSize.value) selectedSize.value = sizesArray.value[0]
  const color = Array.isArray(props.product.colors) && props.product.colors[0] ? props.product.colors[0] : 'Default'
  cart.addItem(props.product, selectedSize.value, color)
  toast.success(`✅ ${props.product.name} added to cart!`)
  addedToCart.value = true
  setTimeout(() => {
    addedToCart.value = false
  }, 1500)
}

function toggleWishlist() {
  const already = isWishlisted.value
  wishlist.toggle(props.product.id)
  toast.info(already ? 'Removed from wishlist' : '❤️ Added to wishlist')
}
</script>

// components/store/ProductCard.tsx
"use client";
import { motion, AnimatePresence } from "framer-motion";
import Link from "next/link";
import Image from "next/image";
import { useState } from "react";
import { Heart, ShoppingBag, Eye } from "lucide-react";
import { useCart } from "@/lib/cartStore";
import toast from "react-hot-toast";

interface Product {
  _id: string;
  name: string;
  slug: string;
  price: number;
  discountPrice?: number;
  images: string[];
  category?: string;
  gender?: string;
  isNewArrival?: boolean;
  isSoldOut?: boolean;
  sizes?: { size: string; stock: number }[];
}

export default function ProductCard({ product }: { product: Product; index?: number }) {
  const [hovered, setHovered] = useState(false);
  const [wishlisted, setWishlisted] = useState(false);
  const [selectedSize, setSelectedSize] = useState<string | null>(null);
  const [showSizes, setShowSizes] = useState(false);
  const { addItem } = useCart();

  const discount = product.discountPrice
    ? Math.round(((product.price - product.discountPrice) / product.price) * 100)
    : null;

  const availableSizes = product.sizes?.filter((s) => s.stock > 0) || [];

  const handleQuickAdd = (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (product.isSoldOut) return;
    if (availableSizes.length <= 1) {
      addItem({
        productId: product._id,
        name: product.name,
        slug: product.slug,
        price: product.price,
        discountPrice: product.discountPrice,
        image: product.images[0],
        size: availableSizes[0]?.size || "M",
        quantity: 1,
      });
      toast.success("Added to bag! ��️", { duration: 2000 });
    } else {
      setShowSizes((prev) => !prev);
    }
  };

  const handleSizeSelect = (e: React.MouseEvent, size: string) => {
    e.preventDefault();
    e.stopPropagation();
    setSelectedSize(size);
    addItem({
      productId: product._id,
      name: product.name,
      slug: product.slug,
      price: product.price,
      discountPrice: product.discountPrice,
      image: product.images[0],
      size,
      quantity: 1,
    });
    toast.success(`Added (${size}) to bag! 🛍️`);
    setShowSizes(false);
  };

  return (
    <motion.div
      className="group relative"
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => {
        setHovered(false);
        setShowSizes(false);
      }}
    >
      <Link href={`/product/${product.slug}`}>
        <div className="relative aspect-[3/4] bg-[#F8F5F0] overflow-hidden rounded-2xl">
          {product.images[0] && (
            <Image
              src={product.images[0]}
              alt={product.name}
              fill
              className={`object-cover transition-all duration-500 ${
                hovered && product.images[1] ? "opacity-0 scale-105" : "opacity-100 scale-100"
              }`}
              sizes="(max-width: 768px) 50vw, 25vw"
            />
          )}

          {product.images[1] && (
            <Image
              src={product.images[1]}
              alt={product.name}
              fill
              className={`object-cover absolute inset-0 transition-all duration-500 ${
                hovered ? "opacity-100 scale-100" : "opacity-0 scale-105"
              }`}
              sizes="(max-width: 768px) 50vw, 25vw"
            />
          )}

          {!product.images[0] && (
            <div className="absolute inset-0 flex items-center justify-center text-4xl">👕</div>
          )}

          <div className="absolute top-3 left-3 flex flex-col gap-1.5 z-10">
            {product.isNewArrival && (
              <span className="bg-[#0A0A0A] text-white text-[10px] px-2.5 py-1 font-black tracking-[0.2em] rounded-full">
                NEW
              </span>
            )}
            {discount && !product.isSoldOut && (
              <span className="bg-[#E63946] text-white text-[10px] px-2.5 py-1 font-black rounded-full">-{discount}%</span>
            )}
            {product.isSoldOut && (
              <span className="bg-gray-500 text-white text-[10px] px-2.5 py-1 font-black tracking-[0.15em] rounded-full">
                SOLD OUT
              </span>
            )}
          </div>

          <button
            onClick={(e) => {
              e.preventDefault();
              e.stopPropagation();
              setWishlisted(!wishlisted);
              toast.success(wishlisted ? "Removed from wishlist" : "Added to wishlist ❤️");
            }}
            className="absolute top-3 right-3 z-10 w-8 h-8 rounded-full bg-white shadow-md flex items-center justify-center transition-transform hover:scale-110"
          >
            <Heart
              size={14}
              className={`transition-colors ${wishlisted ? "fill-[#E63946] text-[#E63946]" : "text-gray-400"}`}
            />
          </button>

          <AnimatePresence>
            {hovered && !showSizes && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="absolute inset-0 flex flex-col items-end justify-end p-3 gap-2 z-10"
              >
                <Link
                  href={`/product/${product.slug}`}
                  onClick={(e) => e.stopPropagation()}
                  className="w-9 h-9 rounded-full bg-white shadow-lg flex items-center justify-center hover:bg-[#0A0A0A] hover:text-white transition-colors"
                >
                  <Eye size={15} />
                </Link>
              </motion.div>
            )}
          </AnimatePresence>

          <AnimatePresence>
            {showSizes && (
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: 10 }}
                className="absolute bottom-14 left-3 right-3 bg-white rounded-xl shadow-xl p-3 z-20"
                onClick={(e) => e.preventDefault()}
              >
                <p className="text-[10px] font-bold tracking-widest text-gray-400 mb-2">SELECT SIZE</p>
                <div className="flex flex-wrap gap-1.5">
                  {availableSizes.map(({ size }) => (
                    <button
                      key={size}
                      onClick={(e) => handleSizeSelect(e, size)}
                      className={`px-3 py-1.5 text-xs font-bold border-2 rounded-lg transition-all ${
                        selectedSize === size
                          ? "bg-[#0A0A0A] text-white border-[#0A0A0A]"
                          : "border-gray-200 hover:border-[#0A0A0A]"
                      }`}
                    >
                      {size}
                    </button>
                  ))}
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          <motion.button
            onClick={handleQuickAdd}
            initial={{ y: 50, opacity: 0 }}
            animate={hovered ? { y: 0, opacity: 1 } : { y: 50, opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="absolute bottom-0 left-0 right-0 py-3 flex items-center justify-center gap-2 text-xs font-black tracking-[0.15em] z-10 rounded-b-2xl transition-colors"
            style={{
              background: product.isSoldOut ? "#9CA3AF" : "#0A0A0A",
              color: "#FFFFFF",
            }}
          >
            <ShoppingBag size={13} />
            {product.isSoldOut ? "SOLD OUT" : availableSizes.length === 1 ? "QUICK ADD" : "SELECT SIZE"}
          </motion.button>
        </div>

        <div className="mt-3 px-0.5">
          <p className="text-[10px] font-bold tracking-[0.2em] text-gray-400 mb-1 uppercase">
            {product.category || "Fashion"} · {product.gender || "Unisex"}
          </p>
          <h3 className="font-semibold text-sm text-[#0A0A0A] leading-snug mb-1.5 line-clamp-2">{product.name}</h3>
          <div className="flex items-center gap-2">
            {product.discountPrice ? (
              <>
                <span className="font-black text-[#E63946] text-base">₹{product.discountPrice}</span>
                <span className="text-gray-400 line-through text-xs">₹{product.price}</span>
              </>
            ) : (
              <span className="font-black text-[#0A0A0A] text-base">₹{product.price}</span>
            )}
          </div>
        </div>
      </Link>
    </motion.div>
  );
}
